apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vikunja
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/7K-Hiroba/vikunja.git
  ref:
    branch: main
