apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Vikunja
  description: Vikunja
  annotations:
    github.com/project-slug: 7K-Hiroba/Vikunja
    backstage.io/docs-url: https://hiroba.7kgroup.org/Vikunja
  tags:
    - kubernetes
spec:
  type: service
  lifecycle: experimental
  owner: group:default/7kgroup
