{{- if and .Values.s3.enabled (eq .Values.s3.provider "crossplane") }}
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: {{ include "platform.name" . }}-{{ .Values.s3.bucketName }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.s3.crossplane.region }}
    acl: {{ .Values.s3.acl }}
    {{- if .Values.s3.crossplane.lifecycle.enabled }}
    lifecycleConfiguration:
      rules:
        - status: Enabled
          filter:
            prefix: ""
          expiration:
            days: {{ .Values.s3.crossplane.lifecycle.expirationDays }}
    {{- end }}
  providerConfigRef:
    name: {{ .Values.s3.crossplane.providerConfigRef }}
{{- end }}
