{{- if and .Values.s3.enabled (eq .Values.s3.provider "garage") }}
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: {{ include "platform.name" . }}-{{ .Values.s3.bucketName }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  clusterRef:
    name: {{ .Values.s3.garage.clusterRef }}
    {{- if .Values.s3.garage.clusterRefNamespace }}
    namespace: {{ .Values.s3.garage.clusterRefNamespace }}
    {{- end }}
  {{- with .Values.s3.garage.quotas }}
  quotas:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.s3.garage.website }}
  website:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.s3.garage.lifecycle }}
  lifecycle:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: {{ include "platform.name" . }}-s3-key
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  clusterRef:
    name: {{ .Values.s3.garage.clusterRef }}
    {{- if .Values.s3.garage.clusterRefNamespace }}
    namespace: {{ .Values.s3.garage.clusterRefNamespace }}
    {{- end }}
  name: "{{ include "platform.name" . }} S3 Key"
  secretTemplate:
    name: {{ include "platform.name" . }}-s3-key
    additionalData:
      S3_BUCKET: "{{ include "platform.name" . }}-{{ .Values.s3.bucketName }}"
  bucketPermissions:
    - bucketRef:
        name: {{ include "platform.name" . }}-{{ .Values.s3.bucketName }}
      read: true
      write: true
{{- if and .Values.s3.garage.clusterRefNamespace (ne .Values.s3.garage.clusterRefNamespace .Release.Namespace) }}
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: {{ include "platform.name" . }}-from-{{ .Release.Namespace }}
  namespace: {{ .Values.s3.garage.clusterRefNamespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  from:
    - kind: GarageKey
      namespace: {{ .Release.Namespace }}
    - kind: GarageBucket
      namespace: {{ .Release.Namespace }}
  to:
    - kind: GarageCluster
      name: {{ .Values.s3.garage.clusterRef }}
{{- end }}
{{- end }}
