apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Vikunja
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hiroba
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/7K-Hiroba/Vikunja.git
      targetRevision: main
      path: helm/base
      helm:
        valueFiles:
          - values.yaml
          # - values-production.yaml  # Uncomment for env-specific overrides
    - repoURL: https://github.com/7K-Hiroba/Vikunja.git
      targetRevision: main
      path: helm/platform
      helm:
        valueFiles:
          - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: Vikunja

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
