name: CI

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  lint-pr-title:
    uses: 7K-Hiroba/workflows-library/.github/workflows/ci-lint-pr-title.yml@main

  helm-base:
    if: >-
      github.event_name == 'pull_request' ||
      contains(toJSON(github.event.commits.*.modified), 'helm/base/')
    uses: 7K-Hiroba/workflows-library/.github/workflows/ci-helm.yml@v1
    with:
      path: helm/base

  helm-platform:
    if: >-
      github.event_name == 'pull_request' ||
      contains(toJSON(github.event.commits.*.modified), 'helm/platform/')
    uses: 7K-Hiroba/workflows-library/.github/workflows/ci-helm.yml@v1
    with:
      path: helm/platform

  docs:
    if: >-
      github.event_name == 'pull_request' ||
      contains(toJSON(github.event.commits.*.modified), 'docs/')
    uses: 7K-Hiroba/workflows-library/.github/workflows/ci-docs.yml@v1
    with:
      path: docs

  crossplane:
    if: >-
      github.event_name == 'pull_request' ||
      contains(toJSON(github.event.commits.*.modified), 'crossplane/')
    uses: 7K-Hiroba/workflows-library/.github/workflows/ci-crossplane.yml@v1
    with:
      path: compositions/crossplane
